name: flutter_charset_detector
description: Detect and decode the charset (character encoding) of text bytes
version: 1.0.2
homepage: https://github.com/amake/flutter_charset_detector

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_charset_detector_android: ^1.0.0
  # flutter_charset_detector_android:
  #   path: ../flutter_charset_detector_android
  flutter_charset_detector_ios: ^1.0.0
  # flutter_charset_detector_ios:
  #   path: ../flutter_charset_detector_ios
  flutter_charset_detector_platform_interface: ^1.0.0
  # flutter_charset_detector_platform_interface:
  #   path: ../flutter_charset_detector_platform_interface

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_charset_detector_android
      ios:
        default_package: flutter_charset_detector_ios
